name: ci
on:
  push:
    branches:
    - master
    - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install jieba
    - run: pip install mkdocs-material
    - run: pip install mkdocs-material-extensions
    - run: pip install mkdocs-abs-rel-plugin
    - run: pip install mkdocs-blogging-plugin
    - run: pip install mkdocs-callouts
    - run: pip install mkdocs-exclude
    - run: pip install mkdocs-exclude-search
    - run: pip install mkdocs-minify-plugin
    - run: pip install mkdocs-redirects
    - run: pip install mkdocs-roamlinks-plugin
    - run: pip install mkdocs-rss-plugin
    - run: pip install mkdocs-video
    - run: pip install mkdocs-glightbox
    - run: pip install pymdown-extensions
    - run: mkdocs gh-deploy --force
